.TH BUI-APPEARANCE "1" "2021" "NNB" "User Commands"
.SH NAME
BUI appearance \- BUI for widget toolkit
.SH SYNOPSIS
.B bui-appearance
.SH DESCRIPTION
BUI appearance is an UI tool written in portable sh that change widget toolkit like GTK and QT setting using BUI environment variables.
.SH ENVIRONMENT VARIABLES
\fBBUI_GTK_THEME or GTK_THEME\fB
GTK theme (Default: Adwaita)
.TP
\fBBUI_GTK_TOOLBAR_STYLE\fB
GTK toolbar style (Default: GTK_TOOLBAR_BOTH)
.TP
\fBBUI_GTK_TOOLBAR_ICON_SIZE\fB
GTK toolbar icon size (Default: GTK_ICON_SIZE_LARGE_TOOLBAR)
.TP
\fBBUI_ICON_THEME\fB
Icon theme (Default: Adwaita)
.TP
\fBBUI_MOUSE_CURSOR_THEME\fB
Mouse cursor theme (Default: Adwaita)
.TP
\fBBUI_MOUSE_CURSOR_SIZE\fB
Border size (Default: 0.0)
.TP
\fBBUI_BUTTON_IMAGES\fB
Button images (Default: true)
.TP
\fBBUI_MENU_IMAGES\fB
Menu images (Default: true)
.TP
\fBBUI_EVENT_SOUNDS\fB
Event sounds (Default: true)
.TP
\fBBUI_INPUT_FEEDBACK_SOUNDS\fB
Input feedback sounds (Default: true)
.TP
\fBBUI_GAPS_SIZE\fB
Gaps size (Default: 0.0)
.TP
\fBBUI_BORDER_SIZE\fB
Border size (Default: 1.0)
.TP
\fBBUI_FONT_FAMILY\fB
Font family (Default: Sans)
.TP
\fBBUI_FONT_SIZE\fB
Font size (Default: 10.0)
.TP
\fBBUI_FONT_ANTIALIAS\fB
Font antialias (Default: true)
.TP
\fBBUI_HINT_STYLE\fB
Hint style (Default: full)
.TP
\fBBUI_SUBPIXEL\fB
Subpixel (Default: none)
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/bui-appearance/issues
